### PR TITLE
Parse named socket port forwards (Fixes #292)

### LINKED ISSUE #292: RemoteForward of UNIX socket fails with SIGABRT
openssh allows `RemoteForward` directives like the following, to proxy UNIX sockets and not just TCP/UDP:
```
RemoteForward /run/user/1000/gnupg/S.gpg-agent /run/user/1000/gnupg/S.gpg-agent.extra
```
Incidentally, this is the preferred way to securely forward access to gpg-agent for remote signing and decryption.

### PR DESCRIPTION
**Pull request by Celti**
As of 1b3a488, forwarding named sockets is supported in the core, but
the only socket accessible to forward was the SSH auth socket.

This is resolved by allowing arbitrary named sockets alongside numeric
port forwards with `-t`/`-r`.

Fixes #292.

--
I am unsure of the changes to `PortForwardHandler.cpp`, so I left it commented instead of removing. Everything _seems_ to work and test fine. I'm very much unfamiliar with C++, apologies if there's something egregiously wrong here.

### CODE REVIEW

File: src/terminal/forwarding/PortForwardHandler.cpp [hunk 1]
```diff
@@ -35,9 +35,9 @@ PortForwardSourceResponse PortForwardHandler::createSource(
     const PortForwardSourceRequest& pfsr, string* sourceName, uid_t userid,
     gid_t groupid) {
   try {
-    if (pfsr.has_source() && !pfsr.source().has_port()) {
-      throw runtime_error("Do not set a source when forwarding named pipes");
-    }
+    /* if (pfsr.has_source() && !pfsr.source().has_port()) { */
+    /*   throw runtime_error("Do not set a source when forwarding named pipes"); */
+    /* } */
```
Comment (MisterTea) [inline src/terminal/forwarding/PortForwardHandler.cpp]:
```suggestion
    if (pfsr.has_source() && sourceName) {
       throw runtime_error("Do not set a source when forwarding named pipes with environment variables"); 
     } 
```

**Comment by MisterTea** [comment]
Hey @Celti please address feedback and rebase to fix tests, thanks.

**Comment by MisterTea** [comment]
@Celti Friendly ping

**Comment by MisterTea** [comment]
Hey @celti can you take a look at this PR feedback?  Otherwise I'll have to close it.

File: src/terminal/forwarding/PortForwardHandler.cpp (hunk 1 above)
Comment (Celti) [reply src/terminal/forwarding/PortForwardHandler.cpp]: Done.

**Comment by Celti** [comment]
Feedback addressed. Apologies for the delay, it hasn't been a happy few months.

**Comment by MisterTea** [comment]
> Feedback addressed. Apologies for the delay, it hasn't been a happy few months.

Totally understand, thanks for updating!
